---
title: "r15"
author: "H"
date: '2019 10 24 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 15-1.R내장함수로 데이터 추출하기

###행번호로 행 추출하기 
```{r cars}
exam<-read.csv("dataSet/csv_exam.csv")
exam[]
```

```{r pressure, echo=FALSE}
exam[1,] #1행추출
```
```{r}
exam[2,]#2행추출
```

###조건을 충족하는 행 추출하기
```{r}
exam[exam$class==1,]
exam[exam$math>=80,]
```

```{r}
#1반이면서 수학점수가 50점 이상
exam[exam$class==1&exam$math>=50,]
```
```{r}
#영어 점수가 90점 미만이거나 과학점수가 50점 미만
exam[exam$english<90|exam$xcience<50,]
```

###열번호로 변수 추출하기
```{r}
exam[,1]#첫번쨰 열 추출
```
```{r}
exam[,2]#두번쨰열 추출
```
```{r}
exam[,3]#세번째열 추출
```

###변수명으로 변수 추출하기
```{r}
exam[,"class"] #class변수 추출
```
```{r}
exam[,"math"] #math 변수 추출
```

```{r}
exam[,c("class","math","english")] #class, math, english 변수 추출
```

###행변수 동시에 추출하기
```{r}
#행, 변수 모두 인덱스
exam[1,3]
```
```{r}
#행 인덱스, 열변수명
exam[5,"english"]
```
```{r}
#행 부등호 조건, 열변수명
exam[exam$math>=50,"english"]
```
```{r}
#행 부등호조건, 열변수명
exam[exam$math>=50, c("english","science")]
```

##dplyr과 내장함수의 차이
###문제)수학점수 50이상, 영어점수 80이상인 학생들을 대상으로 각 반의 전과목 총평균을 구하라
```{r}
#내장함수코드
library(dplyr)
exam$tot<-(exam$math+exam$english+exam$science)/3
####aggregate() 범주별 요약 통계량을 구하는 R내장함수
aggregate(data=exam[exam$math>=50&exam$english>=80,], tot~class,mean)
#dplyr코드
exam %>% filter(math>=50&english>=80) %>% mutate(tot=(math+english+science)/3) %>% group_by(class) %>%  summarise(mean=mean(tot)) 
```


###혼자서해보기 (mpg 데이터를 이용한 분석문제 해결)
```{r}
library(ggplot2)
mpg<-as.data.frame(ggplot2::mpg)  #mpg 데이터 불러오기
 
mpg %>% mutate(tot=(cty+hwy)/2) %>%  #통합연비변수 생성
                 filter(class=="compact"|class=="suv") %>% #compact,suv 추출
                 group_by(class) %>% #class별 분리
                 summarise(mean_tot=mean(tot)) #tot평균 산출

##dplyr 대신 R 내장함수를 이용해 "suv"와 "compact"의 '도시 및 고속도로 통합 연비' 평균 구하기 
mpg$tot<-(mpg$cty+mpg$hwy)/2
df_comp<-mpg[mpg$class=="compact",]
df_suv<-mpg[mpg$class=="suv",]
mean(df_comp$tot)
mean(df_suv$tot)
```

## 15-2.변수타입

###변수 타입 간 차이 알아보기
```{r}
var1<-c(1,2,3,1,2)
var2<-factor(c(1,2,3,1,2))
var1
var2
```

```{r}
var1+2 #numeric 변수로 연산
var2+2 #factor 변수로 연산
```

```{r}
#변수타입 확인하기
class(var1)
class(var2)

#factor변수의 구성범주확인하기
levels(var1)
levels(var2)

#문자로 구성된 factor변수
var3<-c("a","b","b","c")#문자변수생성
var4<-factor(c("a","b","b","c")) #문자로된 factor변수생성
var3
var4

class(var3)
class(var4)

#함수마다 적용가능한 변수 타입이 다르다
mean(var1) # class=numeric
mean(var2) # class=factor
```

###변수타입 바꾸기
```{r}
var2<-as.numeric(var2) #numeric타이브올 변환
mean(var2)

class(var2) #타입확인
levels(var2) #범주확인 #factor였을떄는 [1]"1" "2" "3"
```

###혼자서 해보기
```{r}
#drv 변수의 타입확인
class(mpg$drv)
#drv 변수를 as.factor()을 사용해 factor타입으로 변환한 수 다시 타입확인
mpg$drv<-as.factor(mpg$drv)
class(mpg$drv)
#drv가 어떤 범주로 구성되는지 확인
levels(mpg$drv)
```


##15-3 데이터구조
###데이터 구조 비교하기
####1.벡터
```{r}
#벡터만들기
a<-1
a
b<-"hello"
b

#데이터구조확인
class(a)
class(b)
```

####2.데이터프레임
```{r}
#데이터 프레임 만들기
x1<-data.frame(var1=c(1,2,3), var2=c("a","b","c"))
x1
#데이터 구조 확인
class(x1)
```

####3.매트릭스
```{r}
#매트릭스 만들기 - 1~12로 2열
x2<-matrix(c(1:12),ncol=2)
x2

#데이터 구조 확인
class(x2)
```


####4.어레이
```{r}
#array 만들기 - 1~20으로 2행 *5열*2차원
x3<-array(1:20, dim=c(2,5,2))

#데이터 구조 확인
class(x3)
```

####5.리스트
```{r}
#리스트 생성
x4<-list(f1=a, #벡터
         f2=x1, #데이터프레임
         f3=x2, #매트릭스
         f4=x3) #어레이
x4

#데이터 구조확인
class(x4)

library(ggplot2)
mpg<-ggplot2::mpg
x<-boxplot(mpg$cty)
x

x$stats[,1]#요약 통계량 추출
x$stats[,1][3] #중앙값추출
x$stats[,1][2] #1분위수 추출
```








